version: "3"
services:
  app:
    container_name: api-template
    image: irolegroup/api-express
    environment:
      - DatabaseUrl=mongodb://mongo:27017/iRole-Express-Api
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
